version: "3.8"
networks:
    traefik:
        external: true
services:
    maki-cafe:
        build: .
        restart: always
        labels:
            - traefik.enable=true

            - traefik.http.routers.maki-cafe.rule=Host(`maki.cafe`) || Host(`www.maki.cafe`)
            - traefik.http.routers.maki-cafe.entrypoints=websecure
            - traefik.http.routers.maki-cafe.service=maki-cafe
            - traefik.http.routers.maki-cafe.middlewares=www-to-maki-cafe
            - traefik.http.routers.maki-cafe.tls.certResolver=le
            - traefik.http.services.maki-cafe.loadbalancer.server.port=3000
            
            - traefik.http.middlewares.www-to-maki-cafe.redirectregex.regex=^https?://(?:www\\.)?(.+)
            - traefik.http.middlewares.www-to-maki-cafe.redirectregex.replacement=https://$${1}
            - traefik.http.middlewares.www-to-maki-cafe.redirectregex.permanent=true

            - traefik.docker.network=traefik
        networks:
            - default
            - traefik
