networks:
    traefik:
        external: true
services:
    makidoll-io:
        build: .
        restart: always
        labels:
            - traefik.enable=true

            - >
                traefik.http.routers.makidoll-io.rule=
                Host(`makidoll.io`) || Host(`www.makidoll.io`) ||
                Host(`makidrone.io`) || Host(`www.makidrone.io`) ||
                Host(`maki.cafe`) || Host(`www.maki.cafe`)

            - traefik.http.routers.makidoll-io.entrypoints=websecure
            - traefik.http.routers.makidoll-io.service=makidoll-io
            - traefik.http.routers.makidoll-io.middlewares=www-to-makidoll,maki-cafe-redirect,makidrone-redirect
            - traefik.http.routers.makidoll-io.tls.certResolver=le
            - traefik.http.services.makidoll-io.loadbalancer.server.port=3000

            - traefik.http.middlewares.www-to-makidoll.redirectregex.regex=^https?://(?:www\.)?(.+)
            - traefik.http.middlewares.www-to-makidoll.redirectregex.replacement=https://$${1}
            - traefik.http.middlewares.www-to-makidoll.redirectregex.permanent=true

            - traefik.http.middlewares.maki-cafe-redirect.redirectregex.regex=^https?://(?:www\.)?maki.cafe(.+)
            - traefik.http.middlewares.maki-cafe-redirect.redirectregex.replacement=https://makidoll.io$${1}
            - traefik.http.middlewares.maki-cafe-redirect.redirectregex.permanent=false

            - traefik.http.middlewares.makidrone-redirect.redirectregex.regex=^https?://(?:www\.)?makidrone.io(.+)
            - traefik.http.middlewares.makidrone-redirect.redirectregex.replacement=https://makidoll.io$${1}
            - traefik.http.middlewares.makidrone-redirect.redirectregex.permanent=false

            - traefik.docker.network=traefik
        volumes:
            - ./cache:/app/cache
        networks:
            - default
            - traefik
